# Programming Assignment 2 NUMERICAL PYTHON (NUMPY)

### Problem 1 Normalization Problem

#### Normalization is one of the most basic preprocessing techniques in data analytics. 
#### This involves centering and scaling process. Centering means subtracting the data from the 
#### mean and scaling means dividing with its standard deviation. Mathematically, normalization can be 
#### expressed as: 

     𝑍 =  (𝑋 − 𝑥̅)/𝜎

#### In Python, element-wise mean and element-wise standard deviation can be obtained by using .mean() and .std() calls. 
#### In this problem, create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized 
#### ndarray as X_normalized.npy

In [3]:
#Start

#Import numerical python library
import numpy as np

#Store random 5x5 array in X
X = np.array(np.random.random((5,5)))

#Store and Calculate mean and standard deviation 
mean = X.mean()
std_dev = X.std()

#Calculate normalized array
Z_X = (X - mean)/std_dev

#Save normalized array to 'X_normalized.npy'
np.save('X_normalized.npy', Z_X)
print(Z_X)
#end

[[ 1.48293407  0.54563574  0.40173804 -0.40444156  0.53172264]
 [-1.33656643  1.39518146  1.28356454  0.22754209 -0.59228945]
 [ 0.77143367 -0.85877205 -0.45229671 -1.24569123 -0.42825375]
 [ 0.33605035  1.42142444 -1.03499808  1.40938648 -1.61559311]
 [ 1.41749808 -0.5516239  -1.03775693 -0.47167949 -1.1941489 ]]


### Problem 2: Divisible by 3
#### Create the following 10 x 10 ndarray
#### which are the squares of the first 100 positive integers. 
#### From this ndarray, determine all the elements that are divisible by 3. Save the result as div_by_3.npy

In [19]:
#start

#Import numerical python library
import numpy as np

#Create array of all first 100 positive integers
A = np.array(np.arange(1,101,1))
print(A)
#Resize array to be 10 x 10
A.resize(10,10)
print(A)
#Stores a new array that squared every element by itself
Squared_A = np.square(A)

#Stores every element from Squared_A that is divisible by 3
Div_by_3 = Squared_A[A%3==0]
print(Div_by_3)
#Save array with elements divisble by 3 to 'div_by_3.npy'
np.save('div_by_3.npy',Div_by_3)

#end

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216